name: Pull Request - Validate PR Title

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
  workflow_call:

jobs:
  validate_pr_title:
    name: Validate PR title
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          types: |
            build
            ci
            docs
            feat
            fix
            perf
            refactor
            style
            test
            chore
          subjectPattern: ^(\w{3,4}[-_]*\d+[\s,|]*){1,}([\w\d\s]+)$ # Example: DEV-1234 DEV-1235 Add new feature
